[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer-when-downgrade"

# Force HTTPS
[[redirects]]
  from = "http://dryspacewaterproofing.ca/*"
  to = "https://dryspacewaterproofing.ca/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.dryspacewaterproofing.ca/*"
  to = "https://www.dryspacewaterproofing.ca/:splat"
  status = 301
  force = true

# Redirect www to non-www
[[redirects]]
  from = "https://www.dryspacewaterproofing.ca/*"
  to = "https://dryspacewaterproofing.ca/:splat"
  status = 301
  force = true